version: '3.3'
services:
    mongo:
        image: andregavril/nosql2h20-traffic-mongo
        restart: always
    backend:
        build:
          context: ./backend
        container_name: mse_openstreetmap_backend
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - mongo
    frontend:
        build:
          context: ./frontend
        container_name: mse_openstreetmap_frontend
        ports:
            - "7000:5000"
        depends_on:
            - backend
